**Vitor Salomão - 474028**\
Trabalho 3

In [9]:
#Bibliotecas utilizadas
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score, precision_score


In [12]:
df = pd.read_csv("/content/imoveis_2.csv")
df.drop(columns="title", inplace=True)

In [13]:
df.head()

price    area  bath  room                   tipo      city
0  82692800   744.0   7.0   6.0              Apartment  New York
1  72999000   748.0   6.0   6.0              Apartment  New York
2  69414500  1010.0   6.0   3.0  Residential complexes  New York
3  60795100   663.0   6.0   4.0              Apartment  New York
4  60159200   510.0   3.0   3.0              Apartment  New York

In [14]:
#Transformando o tipo de imóvel em variável dummy
imoveis = df['tipo'].tolist()
for imovel in imoveis:
  df[imovel] = df['tipo'].str.contains(imovel).astype(int)
features = df.columns[0:4]
#Normalização das features na escala Min-Max (0,1)
for feature in features:
  df[feature] = (df[feature]-df[feature].min())/(df[feature].max() - df[feature].min())
df.drop(columns='tipo',inplace=True)

In [15]:
df.head()

price      area      bath      room      city  Apartment  \
0  0.330619  0.061922  0.026201  0.022831  New York          1   
1  0.291835  0.062255  0.021834  0.022831  New York          1   
2  0.277494  0.084090  0.021834  0.009132  New York          0   
3  0.243008  0.055171  0.021834  0.013699  New York          1   
4  0.240464  0.042420  0.008734  0.009132  New York          1   

   Residential complexes  Townhouse  Luxury home  Penthouse  Villa  \
0                      0          0            0          0      0   
1                      0          0            0          0      0   
2                      1          0            0          0      0   
3                      0          0            0          0      0   
4                      0          0            0          0      0   

   Detached House  Duplex  Rural or Farmhouse  Mansion  Hotel  \
0               0       0                   0        0      0   
1               0       0                   0        0      0   
2               0       0                   0        0      0   
3               0       0                   0        0      0   
4               0       0                   0        0      0   

   Semidetached House  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0

In [ ]:
df.info()

In [17]:
#RANDOM FOREST CLASSIFIER
X = df.drop('city', axis=1) #variáveis explicativas
y = df['city'] #variável resposta

# Separando os dados de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

#Treinando o modelo
model = RandomForestClassifier(random_state=100)
model.fit(X_train, y_train)

#Predições
y_pred = model.predict(X_test)

#Métricas do modelo
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

print('Acurácia:', accuracy)
print('Matriz de Confusão:\n', confusion)
print('Precisão:', precision)


Acurácia: 0.7272727272727273
Matriz de Confusão:
 [[ 8  0  0  0  0  0  0]
 [ 1  4  1  1  2  3  1]
 [ 0  0 17  1  1  0  0]
 [ 0  0  1 10  2  0  0]
 [ 2  0  1  1 12  0  0]
 [ 0  1  1  1  2  9  0]
 [ 0  0  1  0  0  0  4]]
Precisão: 0.736261107313739


In [5]:
#NAIVE BAYES
from sklearn.naive_bayes import GaussianNB

X = df.drop('city', axis=1)#variáveis explicativas
y = df['city'] #variável resposta

# Separando os dados de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

#Treinando o modelo
model = GaussianNB()
model.fit(X_train, y_train)

#Predições
y_pred = model.predict(X_test)

#Métricas do modelo
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

print('Acurácia:', accuracy)
print('Matriz de Confusão:\n', confusion)
print('Precisão:', precision)


Acurácia: 0.5
Matriz de Confusão:
 [[ 7  1  0  0  0  0  0]
 [ 1  0  0  0  3  7  2]
 [ 0  0  9  0  0  6  4]
 [ 8  0  1  0  2  0  2]
 [ 1  1  0  0 12  2  0]
 [ 0  1  0  0  1 11  1]
 [ 0  0  0  0  0  0  5]]
Precisão: 0.440563358210417


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [6]:
#SUPORT VECTOR CLASSIFICATION
from sklearn.svm import SVC

X = df.drop('city', axis=1) #variáveis explicativas
y = df['city'] #variável resposta

# Separando os dados de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

#Treinando o modelo
model = SVC()
model.fit(X_train, y_train)

#Predições
y_pred = model.predict(X_test)

#Métricas do modelo
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

print('Acurácia:', accuracy)
print('Matriz de Confusão:\n', confusion)
print('Precisão:', precision)

Acurácia: 0.48863636363636365
Matriz de Confusão:
 [[ 3  0  0  4  0  1  0]
 [ 0  0  5  2  2  4  0]
 [ 0  0 18  0  0  1  0]
 [ 3  0  1  5  0  1  3]
 [ 0  0  1  0  5  9  1]
 [ 1  0  3  0  0 10  0]
 [ 0  0  3  0  0  0  2]]
Precisão: 0.4414747032049085


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [118]:
#GRADIENT BOOSTING CLASSIFIER
from sklearn.ensemble import GradientBoostingClassifier
X = df.drop('city', axis=1) #variáveis explicativas
y = df['city'] #variável resposta

# Separando os dados de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

#Treinando o modelo
model = GradientBoostingClassifier()
model.fit(X_train, y_train)

#Predições
y_pred = model.predict(X_test)

#Métricas do modelo
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

print('Acurácia:', accuracy)
print('Matriz de Confusão:\n', confusion)
print('Precisão:', precision)


Acurácia: 0.6704545454545454
Matriz de Confusão:
 [[ 7  0  0  1  0  0  0]
 [ 1  4  1  1  2  3  1]
 [ 0  0 16  1  1  1  0]
 [ 0  1  1  9  2  0  0]
 [ 1  0  1  4 10  0  0]
 [ 0  1  1  0  3  9  0]
 [ 0  0  1  0  0  0  4]]
Precisão: 0.6733951812076812
